[phases.setup]
nixPkgs = ["python310", "libsndfile", "ffmpeg", "git"]

[phases.install]
cmds = [
    "python -m pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu",
    "python -m pip install -r requirements.txt"
]

[start]
cmd = "streamlit run delyrism/app.py --server.port $PORT --server.address 0.0.0.0"
